/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package datastructuresproject;

import javax.swing.JOptionPane;

/**
 *
 * @author hande
 */
public class BalciDereliEntry extends javax.swing.JFrame {

    /**
     * Creates new form Entry
     */
    public BalciDereliEntry() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btn_start = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Entry");

        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(91, 46, 0));
        jLabel3.setText("PLEASE, ENTER YOUR NAME");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(170, 370, 360, 40);

        btn_start.setBackground(new java.awt.Color(212, 148, 45));
        btn_start.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btn_start.setForeground(new java.awt.Color(73, 53, 10));
        btn_start.setText("LET'S START");
        btn_start.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_startActionPerformed(evt);
            }
        });
        jPanel2.add(btn_start);
        btn_start.setBounds(260, 490, 170, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/datastructuresproject/images/happy_adventurer_250x250.png"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(220, 140, 370, 220);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/datastructuresproject/images/treasure_200x200.png"))); // NOI18N
        jPanel2.add(jLabel4);
        jLabel4.setBounds(470, 510, 240, 180);

        txt_name.setBackground(new java.awt.Color(204, 134, 33));
        txt_name.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        txt_name.setForeground(new java.awt.Color(91, 46, 0));
        txt_name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(127, 87, 12)));
        txt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameActionPerformed(evt);
            }
        });
        jPanel2.add(txt_name);
        txt_name.setBounds(170, 420, 350, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/datastructuresproject/images/parchment_bg_700x700.png"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, 0, 700, 700);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_startActionPerformed
        String username = txt_name.getText().trim();
        BalciDereliPlayer player;
        if (username.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Lütfen kullanıcı adınızı giriniz!", "Uyarı", JOptionPane.WARNING_MESSAGE);
            return;
        } else {
            player = new BalciDereliPlayer(username);
            System.out.println(player.toString());
        }
        player.level=1;
        BalciDereliGameScene gameScene = new BalciDereliGameScene(player);
         this.setVisible(false);
        gameScene.setVisible(true);
        
    }//GEN-LAST:event_btn_startActionPerformed

    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BalciDereliEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BalciDereliEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BalciDereliEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BalciDereliEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BalciDereliEntry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_start;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txt_name;
    // End of variables declaration//GEN-END:variables
}
