/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package datastructuresproject;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Random;
import javax.swing.*;

/**
 *
 * @author hande
 */
public class BalciDereliGameScene extends javax.swing.JFrame {

    /**
     * Creates new form BalciDereliGameScene
     */
    JLabel[] labels;
    BalciDereliPlayer player;
    BalciDereliRoad road;

    public BalciDereliGameScene() {
        initComponents();
    }

    public BalciDereliGameScene(BalciDereliPlayer player) {
        this.player = player;
        initComponents();
        road = new BalciDereliRoad();
        road.createLevel1();
 //       road.printRoad();
        labels = new JLabel[]{
            jLabel1, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6,
            jLabel7, jLabel8, jLabel9, jLabel10, jLabel11, jLabel12,
            jLabel13, jLabel14, jLabel15, jLabel16, jLabel17, jLabel18,
            jLabel19, jLabel20, jLabel21, jLabel22, jLabel23, jLabel24,
            jLabel25, jLabel26, jLabel27, jLabel28, jLabel29, jLabel30
        };
        road.renderToLabels(labels); // haritayı ekrana entegre ettik
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txt_dice = new javax.swing.JLabel();
        dice = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Game Scene");

        jPanel1.setLayout(null);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 30, 60, 60);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(140, 30, 60, 60);
        jPanel1.add(jLabel3);
        jLabel3.setBounds(230, 30, 60, 60);
        jPanel1.add(jLabel4);
        jLabel4.setBounds(315, 30, 60, 60);
        jPanel1.add(jLabel5);
        jLabel5.setBounds(400, 30, 60, 60);
        jPanel1.add(jLabel6);
        jLabel6.setBounds(490, 30, 60, 60);
        jPanel1.add(jLabel7);
        jLabel7.setBounds(580, 100, 60, 60);
        jPanel1.add(jLabel8);
        jLabel8.setBounds(490, 150, 60, 50);
        jPanel1.add(jLabel9);
        jLabel9.setBounds(405, 142, 60, 60);
        jPanel1.add(jLabel10);
        jLabel10.setBounds(320, 150, 60, 50);
        jPanel1.add(jLabel11);
        jLabel11.setBounds(222, 218, 60, 60);
        jPanel1.add(jLabel12);
        jLabel12.setBounds(310, 260, 60, 60);
        jPanel1.add(jLabel13);
        jLabel13.setBounds(400, 260, 60, 60);
        jPanel1.add(jLabel14);
        jLabel14.setBounds(490, 260, 60, 60);
        jPanel1.add(jLabel15);
        jLabel15.setBounds(580, 330, 60, 50);
        jPanel1.add(jLabel16);
        jLabel16.setBounds(580, 430, 60, 50);
        jPanel1.add(jLabel17);
        jLabel17.setBounds(580, 520, 60, 60);
        jPanel1.add(jLabel18);
        jLabel18.setBounds(440, 580, 60, 60);
        jPanel1.add(jLabel19);
        jLabel19.setBounds(350, 580, 60, 60);
        jPanel1.add(jLabel20);
        jLabel20.setBounds(260, 580, 60, 60);
        jPanel1.add(jLabel21);
        jLabel21.setBounds(180, 580, 60, 60);
        jPanel1.add(jLabel22);
        jLabel22.setBounds(250, 470, 60, 60);
        jPanel1.add(jLabel23);
        jLabel23.setBounds(340, 470, 60, 60);
        jPanel1.add(jLabel24);
        jLabel24.setBounds(420, 470, 70, 60);
        jPanel1.add(jLabel25);
        jLabel25.setBounds(370, 350, 60, 60);
        jPanel1.add(jLabel26);
        jLabel26.setBounds(280, 360, 60, 50);
        jPanel1.add(jLabel27);
        jLabel27.setBounds(198, 357, 60, 60);
        jPanel1.add(jLabel28);
        jLabel28.setBounds(110, 360, 60, 60);
        jPanel1.add(jLabel29);
        jLabel29.setBounds(50, 460, 60, 50);
        jPanel1.add(jLabel30);
        jLabel30.setBounds(50, 560, 60, 50);

        txt_dice.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jPanel1.add(txt_dice);
        txt_dice.setBounds(90, 220, 90, 80);

        dice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/datastructuresproject/images/4dice.png"))); // NOI18N
        dice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                diceMouseClicked(evt);
            }
        });
        jPanel1.add(dice);
        dice.setBounds(30, 200, 150, 120);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/datastructuresproject/images/gamescene.png"))); // NOI18N
        jPanel1.add(background);
        background.setBounds(0, 0, 700, 680);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void diceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_diceMouseClicked
        road.printRoad();
        Random rand = new Random();
        int dice = rand.nextInt(6) + 1;
        txt_dice.setText(dice + "");
        int previousLocationId = player.location != null ? player.location.id : -1; // konum null olabilir, kontrol et
        if (previousLocationId != -1) {
            labels[previousLocationId - 1].setIcon(null);
        }

        player.move(dice, road.head,labels);
        // System.out.println("198."+player.location.type);
        labels[player.location.id - 1].setIcon(new ImageIcon(getClass().getResource("/datastructuresproject/images/pawn.png")));
        if (player.location == road.tail) { //  oyun herhangi bir yerde bittiyse
            if (player.level == 1) {
                try (BufferedWriter bw = new BufferedWriter(new FileWriter("score.txt", true))) {
                    bw.write(player.name + ", " + "level" + player.level + ", " + player.score);
                    bw.newLine();
                } catch (IOException e) {
                    e.printStackTrace();
                }
                int choice = JOptionPane.showOptionDialog(
                        this,
                        "Tebrikler " + player.name + "! Level " + player.level + " tamamlandı.\nSkorun: " + player.score + "\nLevel 2'ye geçmek ister misin?",
                        "Level " + player.level + "Bitti",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE,
                        null,
                        new String[]{"Evet", "Hayır, Ana Menüye Dön"},
                        "Evet"
                );
                if (choice == JOptionPane.YES_OPTION) { // devam etmek isterse harite yenileniyor ve her şey sıfırlanıyor.
                    System.out.println("2. LEVEL BASLIYOR...");
                    txt_dice.setText("");
                    player.level++;
                    //yeni road nesnesi 
                    road = new BalciDereliRoad();
                    road = road.createLevel2();
                    player.location = null;
                    player.score = 0;

                    for (JLabel label : labels) {
                        label.setIcon(null);
                    }
                    road.renderToLabels(labels);
                    JOptionPane.showMessageDialog(this, "Level 2 başlıyor!");
                } else { // devam etmek istemezse başlangıç menüsüne yönlendirilir.
                    new BalciDereliStartMenu().setVisible(true);
                    this.dispose();
                }
            } else if (player.level >= 2) {
                JOptionPane.showMessageDialog(this, "Tebrikler " + player.name + "! Level" + player.level + " tamamlandı.\nToplam skorun: " + player.score);
                try (BufferedWriter bw = new BufferedWriter(new FileWriter("score.txt", true))) {
                    bw.write(player.name + ", " + "level" + player.level + ", " + player.score);
                    bw.newLine();
                } catch (IOException e) {
                    e.printStackTrace();
                }
                this.setVisible(false);

            }
        }
    }//GEN-LAST:event_diceMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BalciDereliGameScene.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BalciDereliGameScene.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BalciDereliGameScene.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BalciDereliGameScene.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BalciDereliGameScene().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel dice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txt_dice;
    // End of variables declaration//GEN-END:variables
}
