/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package datastructuresproject;

import javax.swing.JOptionPane;

/**
 *
 * @author hande
 */
public class BalciDereliStartMenu extends javax.swing.JFrame {

    /**
     * Creates new form StartMenu
     */
    public BalciDereliStartMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_start = new javax.swing.JButton();
        btn_scoreboard = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Start Menu");

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(91, 46, 0));
        jLabel2.setText("TREASURE");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(190, 40, 200, 50);

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(91, 46, 0));
        jLabel3.setText("HUNT");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(410, 40, 120, 50);

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(91, 46, 0));
        jLabel4.setText("ADVENTURE");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(230, 90, 270, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/datastructuresproject/images/character_v2_250x250.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(210, 190, 260, 260);

        btn_start.setBackground(new java.awt.Color(212, 148, 45));
        btn_start.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btn_start.setForeground(new java.awt.Color(73, 53, 10));
        btn_start.setText("START GAME");
        btn_start.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_startActionPerformed(evt);
            }
        });
        jPanel1.add(btn_start);
        btn_start.setBounds(250, 450, 170, 40);

        btn_scoreboard.setBackground(new java.awt.Color(212, 148, 45));
        btn_scoreboard.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btn_scoreboard.setForeground(new java.awt.Color(73, 53, 10));
        btn_scoreboard.setText("SCOREBOARD");
        btn_scoreboard.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_scoreboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_scoreboardActionPerformed(evt);
            }
        });
        jPanel1.add(btn_scoreboard);
        btn_scoreboard.setBounds(250, 510, 170, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/datastructuresproject/images/treasure_map_bg_700x700.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 700, 690);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_startActionPerformed
        BalciDereliEntry entryFrame = new BalciDereliEntry(); // isim girilecek frame
        entryFrame.setVisible(true);
    }//GEN-LAST:event_btn_startActionPerformed

    private void btn_scoreboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_scoreboardActionPerformed
        BalciDereliScoreBoard scoreBoard = new BalciDereliScoreBoard(); //scoreborad framei
        scoreBoard.setVisible(true);
    }//GEN-LAST:event_btn_scoreboardActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BalciDereliStartMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BalciDereliStartMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BalciDereliStartMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BalciDereliStartMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BalciDereliStartMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_scoreboard;
    private javax.swing.JButton btn_start;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
