/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package datastructuresproject;

import javax.swing.JOptionPane;

/**
 *
 * @author hande
 */
public class BalciDereliScoreBoard extends javax.swing.JFrame {

    /**
     * Creates new form ScoreBoard
     */
    public BalciDereliScoreBoard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_best = new javax.swing.JLabel();
        txt_searchName = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txt_worst = new javax.swing.JLabel();
        txt_all = new javax.swing.JLabel();
        txt_username = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_area = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Score Board");

        jPanel1.setLayout(null);

        txt_best.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        txt_best.setForeground(new java.awt.Color(91, 46, 0));
        txt_best.setText("BEST SCORE:");
        jPanel1.add(txt_best);
        txt_best.setBounds(50, 490, 610, 40);

        txt_searchName.setBackground(new java.awt.Color(212, 148, 45));
        txt_searchName.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        txt_searchName.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txt_searchName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchNameActionPerformed(evt);
            }
        });
        jPanel1.add(txt_searchName);
        txt_searchName.setBounds(50, 100, 520, 30);

        jButton1.setBackground(new java.awt.Color(212, 148, 45));
        jButton1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(91, 46, 0));
        jButton1.setText("SEARCH");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(590, 100, 90, 21);

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(91, 46, 0));
        jLabel4.setText("PLEASE, ENTER YOUR NAME FOR SEARCH");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 40, 540, 40);

        txt_worst.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        txt_worst.setForeground(new java.awt.Color(91, 46, 0));
        txt_worst.setText("WORST SCORE:");
        jPanel1.add(txt_worst);
        txt_worst.setBounds(50, 560, 260, 40);

        txt_all.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        txt_all.setForeground(new java.awt.Color(91, 46, 0));
        txt_all.setText("ALL SCORES:");
        jPanel1.add(txt_all);
        txt_all.setBounds(50, 240, 120, 30);

        txt_username.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        txt_username.setForeground(new java.awt.Color(91, 46, 0));
        txt_username.setText("USERNAME:");
        jPanel1.add(txt_username);
        txt_username.setBounds(50, 180, 610, 40);

        jScrollPane1.setAutoscrolls(true);

        txt_area.setBackground(new java.awt.Color(212, 148, 45));
        txt_area.setColumns(20);
        txt_area.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        txt_area.setForeground(new java.awt.Color(91, 46, 0));
        txt_area.setRows(5);
        jScrollPane1.setViewportView(txt_area);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(180, 240, 470, 240);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/datastructuresproject/images/parchment_bg_700x700.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 700, 640);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String playerName = txt_searchName.getText().trim();
        BalciDereliBST bst = new BalciDereliBST();
        boolean found = bst.readScoreFile(playerName);
        if (found) {
            StringBuilder allScores = new StringBuilder();
            bst.AllTheScores(bst.root, allScores);
            txt_username.setText(txt_username.getText() + " " + playerName);
            txt_area.setText(allScores.toString());
            BalciDereliBNode findMin = bst.findMin(bst.root);
            BalciDereliBNode findMax = bst.findMax(bst.root);
            txt_worst.setText(txt_worst.getText() + " " + findMin.score + " " + "(level" + findMin.level + ")");
            txt_best.setText(txt_best.getText() + " " + findMax.score + " " + "(level" + findMax.level + ")");
        }else{
         JOptionPane.showMessageDialog(this,
                    "Bu kullanıcı adına ait skor bulunamadı.",
                    "Uyarı",
                    JOptionPane.WARNING_MESSAGE);
        }
        txt_searchName.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_searchNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BalciDereliScoreBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BalciDereliScoreBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BalciDereliScoreBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BalciDereliScoreBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BalciDereliScoreBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel txt_all;
    private javax.swing.JTextArea txt_area;
    private javax.swing.JLabel txt_best;
    private javax.swing.JTextField txt_searchName;
    private javax.swing.JLabel txt_username;
    private javax.swing.JLabel txt_worst;
    // End of variables declaration//GEN-END:variables
}
